<?php 
include_once('include/header.php'); 
?>
<div class="content-wrapper">
    <section class="content-header">
		<h1>Category<small>Manage</small></h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li><a href="#">Category</a></li>
			<li class="active">List</li>
		</ol>
    </section>

    <!-- Main content -->
    <section class="content">
		<?php
		if(isset($_SESSION['success']))
		{
			echo $_SESSION['success'];
			unset($_SESSION['success']);
		}
		if(isset($_SESSION['error']))
		{
			echo $_SESSION['error'];
			unset($_SESSION['error']);
		}
		?>
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">All Category</h3>
					</div>
   
					<div class="box-body">
						<table id="bootstrap-data-table" class="table table-striped table-bordered DataTable">
							<thead>
								<tr>
									<th>S.No.</th>
									<th>Name</th>
									<th>Logo</th>
									<th>Main Category</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
								<tr>
									<td>1</td>
									<td>Anil</td>
									<td>Sunil</td>
									<td>Test1</td>
									<td>Text1</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
    </section>
</div>
<?php include_once('include/footer.php'); ?>
